import * as type from './type.config';
import * as settingMap from './settingMap.config';
import * as API from './API';

export { API, type, settingMap };
export { awaitHash } from './awaitHash';
export { addCommas } from './addCommas';
export { cleanEmptyObj } from './cleanEmptyObj';
export { encrypt } from './encrypt';
export { getDisplayName } from './playground_utils/getDisplayName';
export { getFirstDigitFromInteger } from './playground_utils/getFirstDigitFromInteger';
export { getPrizeAmount } from './playground_utils/getPrizeAmount';
export { getSettingKey } from './playground_utils/getSettingKey';
export { getSymbolicName } from './playground_utils/getSymbolicName';
export { isLastItem } from './isLastItem';
export { multiset } from './accessStorage';
export { newStyle } from './newStyle';
export { numberGenerators } from './numberGenerators';
export { request, requestMethod } from './request';
export { stripUnit } from './stripUnit';
export { strPropCheck } from './strPropCheck';
export { testStr } from './testStr';
export { toLettercase } from './lettercase';
export { getRandomInt } from './getRandomInt';
export { trimSpecialChar } from './trimSpecialChar';
